Fix encoding issue on Windows 11
Summary:
The `make_models.py` python script fails on Windows due to an encoding issue when reading the live spec json (see below error).

```
(venv) PS C:\Users\roman\Documents\TestProject\models> python make_models.py
torch version 1.10.0+cpu
Exporting image classification models
Exporting model resnet18
Model resnet18 successfully exported
Exporting model mobilenet_v3_large
Model mobilenet_v3_large successfully exported
Exporting model mobilenet_v3_small
Model mobilenet_v3_small successfully exported
Exporting image segmentation models
C:\Users\roman/.cache\torch\hub\facebookresearch_detr_main\util\misc.py:338: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  max_size_i = torch.max(torch.stack([img.shape[i] for img in tensor_list]).to(torch.float32)).to(torch.int64)
C:\Users\roman/.cache\torch\hub\facebookresearch_detr_main\util\misc.py:348: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for img in tensor_list:
C:\Users\roman/.cache\torch\hub\facebookresearch_detr_main\models\position_encoding.py:41: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_pos_feats)
Exporting MNIST model
Model mnist successfully exported
Exporting NLP models
C:\Users\roman\Documents\TestProject\venv\lib\site-packages\transformers\modeling_utils.py:1967: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert all(
Traceback (most recent call last):
  File "C:\Users\roman\Documents\TestProject\models\make_models.py", line 124, in <module>
    main()
  File "C:\Users\roman\Documents\TestProject\models\make_models.py", line 120, in main
    export_nlp_models()
  File "C:\Users\roman\Documents\TestProject\models\make_models.py", line 113, in export_nlp_models
    bundle_live_spec_and_export_model("bert_qa", traced_model)
  File "C:\Users\roman\Documents\TestProject\models\make_models.py", line 27, in bundle_live_spec_and_export_model
    spec = Path(f"{name}.{MODEL_EXTENSION}.live.spec.json").read_text()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1267, in read_text
    return f.read()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 13247: character maps to <undefined>
```

Adding the `utf-8` encoding when reading the live spec as text solves the issue on Windows 11.

The `make_models.py` python script succeeds with the `utf-8` change.

Reviewed By: liuyinglao

Differential Revision: D33272689

fbshipit-source-id: bb0a069d50c425a3032c512ba2b7c140183d5229