Upgrade to React Native 0.64.2
Summary:
Updated React Native to 0.64.2 and other dependencies to work with Xcode 12.5 (and iOS 14.6).

It also required to add a `DummySwift.swift` file to the template for Xcode to pick up `swiftWebKit`.

```
ld: warning: Could not find or use auto-linked library 'swiftWebKit'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_react_native_pytorch_core in libreact-native-pytorch-core.a(PyTorchCore-f5f7a9a3ee8b4b2def7c8b0cf4b1f1fff62fbf09bb47013c34f9c0349874f383.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_react_native_pytorch_core)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld /Users/raedle/Library/Developer/Xcode/DerivedData/PyTorchLiveExample-bbnenjdoxpyddrfkjiiupkzpkvyp/Build/Products/Debug-iphonesimulator/PyTorchLiveExample.app/PyTorchLiveExample normal
(1 failure)
```

allow-large-files

Reviewed By: castillejoale

Differential Revision: D28955366

fbshipit-source-id: c286d87edff3f59a630c50f21fe43bc6b1cbec4e