Fix broken pytorch-live job
Summary:
The `pytorch-live` job fails with an error due to `yarn tsc` failing for the `template` project (see error below).

This started happening with D29221226 adding detox. The diff makes lots of version updates in `yarn.lock`, which eventually introduces version conflicts with other package dependencies.

This change reverts the `yarn.lock` and only adds `detox` and `jest-circus` as dependencies.

```
yarn tsc
Using Yarn from /data/sandcastle/boxes/fbsource/xplat/third-party/yarn/yarn
yarn run v1.17.0-20190429.1820
$ /data/sandcastle/boxes/fbsource/xplat/pytorch/live/react-native-template-pytorch-live/template/node_modules/.bin/tsc
Done in 3.98s.
[raedle@65488.od /data/sandcastle/boxes/fbsource/xplat/pytorch/live/react-native-template-pytorch-live/template (e7ac811d4)]$ cp _gitignore .gitignore
[raedle@65488.od /data/sandcastle/boxes/fbsource/xplat/pytorch/live/react-native-template-pytorch-live/template (e7ac811d4)]$ cp _gitignore .gitignore
[raedle@65488.od /data/sandcastle/boxes/fbsource/xplat/pytorch/live/react-native-template-pytorch-live/template (e7ac811d4)]$ yarn tsc
Using Yarn from /data/sandcastle/boxes/fbsource/xplat/third-party/yarn/yarn
yarn run v1.17.0-20190429.1820
$ /data/sandcastle/boxes/fbsource/xplat/pytorch/live/react-native-template-pytorch-live/template/node_modules/.bin/tsc
node_modules/types/node/globals.d.ts:317:11 - error TS2300: Duplicate identifier 'AbortController'.

317 interface AbortController {
              ~~~~~~~~~~~~~~~

  node_modules/types/react-native/globals.d.ts:389:15
    389 declare class AbortController {
                      ~~~~~~~~~~~~~~~
    'AbortController' was also declared here.

node_modules/types/node/globals.d.ts:330:11 - error TS2300: Duplicate identifier 'AbortSignal'.

330 interface AbortSignal {
              ~~~~~~~~~~~

  node_modules/types/react-native/globals.d.ts:376:15
    376 declare class AbortSignal {
                      ~~~~~~~~~~~
    'AbortSignal' was also declared here.

node_modules/types/node/globals.d.ts:337:13 - error TS2300: Duplicate identifier 'AbortController'.

337 declare var AbortController: {
                ~~~~~~~~~~~~~~~

  node_modules/types/react-native/globals.d.ts:389:15
    389 declare class AbortController {
                      ~~~~~~~~~~~~~~~
    'AbortController' was also declared here.

node_modules/types/node/globals.d.ts:342:13 - error TS2300: Duplicate identifier 'AbortSignal'.

342 declare var AbortSignal: {
                ~~~~~~~~~~~

  node_modules/types/react-native/globals.d.ts:376:15
    376 declare class AbortSignal {
                      ~~~~~~~~~~~
    'AbortSignal' was also declared here.

node_modules/types/react-native/globals.d.ts:376:15 - error TS2300: Duplicate identifier 'AbortSignal'.

376 declare class AbortSignal {
                  ~~~~~~~~~~~

  node_modules/types/node/globals.d.ts:330:11
    330 interface AbortSignal {
                  ~~~~~~~~~~~
    'AbortSignal' was also declared here.
  node_modules/types/node/globals.d.ts:342:13
    342 declare var AbortSignal: {
                    ~~~~~~~~~~~
    and here.

node_modules/types/react-native/globals.d.ts:389:15 - error TS2300: Duplicate identifier 'AbortController'.

389 declare class AbortController {
                  ~~~~~~~~~~~~~~~

  node_modules/types/node/globals.d.ts:317:11
    317 interface AbortController {
                  ~~~~~~~~~~~~~~~
    'AbortController' was also declared here.
  node_modules/types/node/globals.d.ts:337:13
    337 declare var AbortController: {
                    ~~~~~~~~~~~~~~~
    and here.

Found 6 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Reviewed By: zrfisher

Differential Revision: D29413330

fbshipit-source-id: 7a46917e0add8dffc8de1b169f8983090d21574e