Enable broken link check for markdown
Summary:
Starting with Docusaurus beta.1, the website supports broken link checks for markdown (md,mdx) files. It's enabled by setting the `trailingSlash: true` flag in the `docusaurus.config.js`.

With this check enabled, the page build fails with the following broken links.

```
Unable to build website for locale "en".
Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /live/docs/tutorials/connecting-to-a-server/:
   -> linking to get-started/ (resolved as: /live/docs/tutorials/connecting-to-a-server/get-started/)

- On source page path = /live/docs/tutorials/image-classification/:
   -> linking to get-started/ (resolved as: /live/docs/tutorials/image-classification/get-started/)
   -> linking to prepare-custom-model/ (resolved as: /live/docs/tutorials/image-classification/prepare-custom-model/)

- On source page path = /live/docs/tutorials/mnist-digit-classification/:
   -> linking to get-started/ (resolved as: /live/docs/tutorials/mnist-digit-classification/get-started/)

- On source page path = /live/docs/tutorials/question-answering/:
   -> linking to get-started/ (resolved as: /live/docs/tutorials/question-answering/get-started/)
   -> linking to prepare-custom-model/ (resolved as: /live/docs/tutorials/question-answering/prepare-custom-model/)

    at Object.reportMessage (<PROJECT>/website/node_modules/docusaurus/utils/lib/index.js:358:19)
    at Object.handleBrokenLinks (<PROJECT>/website/node_modules/docusaurus/core/lib/server/brokenLinks.js:142:17)
    at async buildLocale (<PROJECT>/website/node_modules/docusaurus/core/lib/commands/build.js:160:5)
    at async tryToBuildLocale (<PROJECT>/website/node_modules/docusaurus/core/lib/commands/build.js:32:20)
    at async Object.mapAsyncSequencial (<PROJECT>/website/node_modules/docusaurus/utils/lib/index.js:313:24)
    at async build (<PROJECT>/website/node_modules/docusaurus/core/lib/commands/build.js:68:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
�  Done in 41.12s.
```

This fixes the broken links!

Great feature in Docusaurus! Pure gold!

Reviewed By: liuyinglao

Differential Revision: D33025752

fbshipit-source-id: 0898d5b008df283636ef8da065fe67dbba312c02