Add centerCrop function to support vision models
Summary:
In this diff, we load the scripted CenterCrop operator and apply it to a tensor.

In this case, we can call the centerCrop operator like this

```
const tensor = torch.rand([20, 3, 1024, 1024]);
const centerCrop = __torchlive_torchvision__.transforms.centerCrop(480);
const centerCropped = centerCrop.fowrard(tensor);
console.log(centerCropped.shape // [20 ,3, 480, 480]
```

This imitates PyTorch behavior:
```
import torchvision.transforms as T
>>> cc = T.CenterCrop([40])
>>> cc = T.CenterCrop([40,40])
>>> cc = T.CenterCrop(40)

>>> cc = T.CenterCrop(40,50)
TypeError: __init__() takes 2 positional arguments but 3 were given
>>> cc = T.CenterCrop()
TypeError: __init__() missing 1 required positional argument: 'size'
>>> cc = T.CenterCrop([])
ValueError: Please provide only two dimensions (h, w) for size.
>>> cc = T.CenterCrop([40,40,40])
ValueError: too many values to unpack (expected 2)"
```

the header file are generated like this

```
xxd -i center_crop_scriptmodule.ptl > center_crop_scriptmodule.h
```

Reviewed By: raedle

Differential Revision: D34404763

fbshipit-source-id: ce7bc4356ecc07501bcab741b48bd2d25a1d7c2b